language: python
sudo: true
dist: xenial

env:
  
  - LUA="lua 5.3" 

before_install:
  - pip install hererocks
  - hererocks HERE --$LUA --no-readline --luarocks latest --verbose
  - hererocks HERE --show
  - source HERE/bin/activate
  - sudo apt-get install cmake
  - sudo apt-get install libhttp-parser-dev
  - sudo apt install libssh2-1-dev
  - sudo apt install libcurl4-openssl-dev
  - sudo apt-get install liblua5.3-dev
  - chmod +x ./install_libgit.sh
  - "./install_libgit.sh"

install:
  - luarocks install luacheck
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install busted
  - sudo apt-get update
  - mkdir build && cd build
  - cmake ..
  - sudo make install
  - echo " INSTALL SUCCESSFUL USING CMAKE/MAKE "
  - cd ..
  - luarocks make luagit2-0.0-1.rockspec 
  - echo " INSTALL SUCCESSFUL USING LUAROCKS "
  
script:
  - echo "Successful build"

notifications:
  email:
    on_success: change
on_failure: always